name = "streams"
main = "src/worker.js"
compatibility_date = "2024-09-25"

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "none"

[assets.routing]
has_user_worker = true
